config/routes.rb
Rails.application.routes.draw do

   root 'users#index'
    resources :people, :users
    get 'login', :to => 'user_sessions#new'
    post '/user_sessions', :to => 'user_sessions#create', as: :user_sessions 
    get 'logout', :to => 'user_sessions#destroy'

end

app/models/person.rb
class Person < ActiveRecord::Base
	mount_uploader :image,ImageUploader 

	#searchable do 
	#	text :name, :age, :email, :born_date,:city 
	#end

	def self.search(term)
		self.where('name LIKE :term OR age LIKE :term OR email LIKE :term OR born_date LIKE :term OR city LIKE :term' , term: "%#{term}%")
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	acts_as_authentic
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	helper_method :current_user

	private

	def current_user_session
	  return @current_user_session if defined?(@current_user_session)
	  @current_user_session = UserSession.find
	end

	def current_user
	  return @current_user if defined?(@current_user)
	  @current_user = current_user_session && current_user_session.record
	end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  #autocomplete :person, :name, :full =>true ,:extra_data => [:email]

  def index
    if params[:search].present?
      @people = Person.search params[:search]
    else
      @people = Person.all
    end
    respond_to do |format|
      format.html
      format.json { @people = Person.search(params[:term]) }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:image,:name, :age, :email, :born_date, :city, :remote_image_url)
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
	def new
		@user_session = UserSession.new
	end
	def create
	  @user_session = UserSession.new(user_session_params)
	  if @user_session.save
	    flash[:notice] = "Successfully logged in."
	    redirect_to people_path
	  else
	    render :action => 'new'
	  end
	end

	def destroy
	  @user_session = UserSession.find
	  @user_session.destroy
	  flash[:notice] = "Successfully logged out."
	  redirect_to root_url
	end

	private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_session
      @user = user_session.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_session_params
      params.require(:user_session).permit(:username,  :password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Registration successful."
      redirect_to people_path
    else
      render :action => 'new'
    end
  end

  def index
    @users = User.all
  end

  def update
    if @user.update_attributes(user_params)
      flash[:notice] = "Successfully updated profile."
      redirect_to people_path
    else
      render :action => 'edit'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username,  :email, :password,:password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RoR101</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="wrapper">
    <div class="field">
      <%= f.label :image %><br>
      <%= f.file_field :image%>
    </div>
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name%>
    </div>
    <div class="field">
      <%= f.label :age %><br>
      <%= f.number_field :age %>
    </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :born_date %><br>
      <%= f.date_select :born_date, start_year: 1920 %>
    </div>
      <div class="field">
      <%= f.label :city %><br>
      <%= f.text_field :city %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<p>
	<!--<strong>Image:</strong>-->
	<%= image_tag(@person.image,width:230,height:230) %></p>
<p>
<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Contacts</h1>

<%= form_tag people_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, nil ,placeholder: "Search" %>
  </p>
  <div class="people-search">
    <div class="results" id="people-search-results"></div>
  </div>
<% end %>

<div id="cancel"><input type="text" name="cancel" placeholder="Cancel"></div>


<div id="user_nav">
  <% if current_user %>
    <%= link_to "Edit Profile", edit_user_path(:current) %> |
    <%= link_to "Logout", logout_path %>
  <% end %>
</div>


<table class="wrapper">
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Age</th>
      <th>Email</th>
      <th>Born date</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= image_tag(person.image,width:30,height:30) %></td>
        <td><%= person.name %></td>
        <td><%= person.age %></td>
        <td><%= person.email %></td>
        <td><%= person.born_date %></td>
        <td><%= person.city %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<footer>
  <%= link_to '+', new_person_path %>
</footer>
<script>
  $(function() {
    new app.People;
  });
</script>

app/views/people/new.html.erb
<h1>New Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<!--<strong>Image:</strong>-->
	<%= image_tag(@person.image,width:230,height:230) %></p>
<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @person.age %>
</p>

<p>
  <strong>Email:</strong>
  <%= @person.email %>
</p>

<p>
  <strong>Born date:</strong>
  <%= @person.born_date %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= form_for(@user_session) do |f| %>
  <% if @user_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_session.errors.count, "error") %>prohibited this user_session from being saved:</h2>
      <ul>
      <% @user_session.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="wrapper">
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
  <%= f.submit "Submit" %></p>
  </div>
<% end %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="wrapper">
  <div class="field"
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field"
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div
<% end %>
</div>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/users/index.html.erb
<div class="wrapper">
<div class="logo">
	<h1>Sweet Robot Date</h1>
	<h2>international robot dating agency</h2>
</div>
<div class = "img">
	<img src="assets/robot_couple.png" height="420px" width="420px">
</div>
<div class="phrase">
<h1>Choose Your Soul Mate</h1>
<h2>from 300.000+ lonely robot hearts</h2>
</div>

<%= link_to "Register", new_user_path %> |
<%= link_to "Login", login_path %>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>